import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { createFontStack } from "@capsizecss/core";
import eBGaramond from "@capsizecss/metrics/eBGaramond";
import georgia from "@capsizecss/metrics/georgia";
import timesNewRoman from "@capsizecss/metrics/timesNewRoman";
import courierNew from "@capsizecss/metrics/courierNew";
import arial from "@capsizecss/metrics/arial";
import { fromBuffer } from "@capsizecss/unpack";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");

const iosevkaWoff2 = resolve(
  repoRoot,
  "node_modules/@fontsource/iosevka/files/iosevka-latin-400-normal.woff2",
);

const iosevkaUnpacked = await fromBuffer(await readFile(iosevkaWoff2));
const iosevka = {
  familyName: "Iosevka",
  category: iosevkaUnpacked.category,
  capHeight: iosevkaUnpacked.capHeight,
  ascent: iosevkaUnpacked.ascent,
  descent: iosevkaUnpacked.descent,
  lineGap: iosevkaUnpacked.lineGap,
  unitsPerEm: iosevkaUnpacked.unitsPerEm,
  xHeight: iosevkaUnpacked.xHeight,
  xWidthAvg: iosevkaUnpacked.xWidthAvg,
};

const ebGaramondVariable = { ...eBGaramond, familyName: "EB Garamond Variable" };

const serif = createFontStack(
  [ebGaramondVariable, georgia, timesNewRoman, arial],
  { fontFaceProperties: { fontDisplay: "swap" } },
);

const mono = createFontStack([iosevka, courierNew], {
  fontFaceProperties: { fontDisplay: "swap" },
});

const css = `/* Generated by scripts/generate-fonts.ts — do not edit by hand. */
/* Capsize fallback @font-face overrides eliminate layout shift while web fonts load. */

${serif.fontFaces}
${mono.fontFaces}

:root {
  --font-serif-stack: ${serif.fontFamily};
  --font-mono-stack: ${mono.fontFamily};
}
`;

const out = resolve(repoRoot, "src/fonts.css");
await writeFile(out, css, "utf8");
console.log(`Wrote ${out}`);
